export type Project = { id: string; title: string; category: string; kind: 'video' | 'image'; src: string; poster: string; alt: string; aspect: string; duration?: string; gallery?: string[] };
export const projects: Project[] = [
 { id:'01',title:'UNIQLO',category:'Indoor / Fashion / UGC',kind:'video',src:'/assets/videos/uniqlo-indoor.mp4',poster:'/assets/work/uniqlo-indoor.webp',alt:'A UNIQLO indoor try-on featuring brown wide-leg trousers and a white camisole.',aspect:'1440 / 2228',duration:'00:11' },
 { id:'02',title:'UNIQLO',category:'Outdoor / Fashion / UGC',kind:'video',src:'/assets/videos/uniqlo-outdoor.mp4',poster:'/assets/work/uniqlo-outdoor.webp',alt:'A creator wearing a burgundy linen dress outdoors.',aspect:'1440 / 2252',duration:'00:18' },
 { id:'03',title:'BRUNELLO CUCINELLI',category:'Cinematic commercial film',kind:'video',src:'/assets/videos/brunello-cinematic.mp4',poster:'/assets/work/brunello-film.webp',alt:'Linen and knitwear in a sunlit Italian villa setting.',aspect:'2528 / 1440',duration:'00:28' },
 { id:'05',title:'CLOUD NINE',category:'Splash Pops / Fragrance / UGC',kind:'video',src:'/assets/videos/cloud-nine-splash-pops.mp4',poster:'/assets/work/cloud-nine.webp',alt:'A creator in a white robe presents a pink Splash Pops fragrance bottle.',aspect:'1440 / 2580',duration:'00:44' },
 { id:'06',title:'BRUNELLO CUCINELLI',category:'Product / Hyper-motion',kind:'video',src:'/assets/videos/brunello-product-motion.mp4',poster:'/assets/work/brunello-motion.webp',alt:'A close view of intricate natural-fibre knitwear and sequin embellishments.',aspect:'3090 / 1440',duration:'00:18' },
 { id:'07',title:'TIFFANY',category:'Jewelry / Product story',kind:'video',src:'/assets/videos/tiffany-product-story.mp4',poster:'/assets/work/tiffany-story.webp',alt:'A diamond necklace developed from a jewelry sketch.',aspect:'3090 / 1440',duration:'00:14' },
 { id:'08',title:'TIFFANY',category:'Jewelry / Brand cinematic',kind:'video',src:'/assets/videos/tiffany-brand-cinematic.mp4',poster:'/assets/work/tiffany-film.webp',alt:'A woman wearing a diamond necklace in a cinematic, low-lit setting.',aspect:'2542 / 1440',duration:'00:47' },
 { id:'09',title:'AURA ROYALE',category:'Fragrance / Hyper-motion',kind:'video',src:'/assets/videos/aura-royale-motion.mp4',poster:'/assets/work/aura-motion.webp',alt:'Aura Royale perfume framed by dark liquid and sculptural reflections.',aspect:'1440 / 2560',duration:'00:06' },
 { id:'10',title:'AURA ROYALE',category:'Fragrance / Product photography',kind:'image',src:'/assets/work/aura-original.jpg',poster:'/assets/work/aura-original.jpg',alt:'The original Aura Royale bottle and black box on a dark stone surface.',aspect:'4 / 3' },
];
export const extraProjects: Project[] = [
 { id:'ember',title:'EMBER HOUSE',category:'Product film / Photography / Packaging',kind:'video',src:'/assets/videos/ember-house-film.mp4',poster:'/assets/work/ember-film.webp',alt:'Purple ceramic candle with a gold lid.',aspect:'1 / 1',duration:'00:15',gallery:['/assets/work/ember-home.webp','/assets/work/ember-fireplace.webp','/assets/work/ember-packaging.webp'] },
 { id:'noor-pour',title:'NOOR & BEAN',category:'Cold brew / Product film',kind:'video',src:'/assets/videos/noor-bean-product.mp4',poster:'/assets/work/noor-pour.webp',alt:'Cold brew coffee pouring over ice.',aspect:'16 / 9',duration:'00:15',gallery:['/assets/work/noor-poster.webp','/assets/work/noor-logo.webp'] },
 { id:'noor-lifestyle',title:'NOOR & BEAN',category:'Cold brew / Lifestyle film',kind:'video',src:'/assets/videos/noor-bean-lifestyle.mp4',poster:'/assets/work/noor-life.webp',alt:'A couple share cold brew coffee in a kitchen.',aspect:'16 / 9',duration:'00:15' },
];
export const identityProject: Project = { id:'identity',title:'VESAGE / LAB',category:'Form, light, image. An identity experiment.',kind:'video',src:'/assets/world/scene-01.mp4',poster:'/assets/world/scene-01-poster.png',alt:'A black silk sculpture illuminated by a restrained silver highlight.',aspect:'16 / 9',duration:'00:15' };
